export { default as BfsiHeroImage } from "../assets/bfsi/bfsi_hero_banner.svg";
export { default as CapitalMarketingImage } from "../assets/bfsi/capital_marketing.png";
export { default as ClaimManagementImage } from "../assets/bfsi/claim_managment.svg";
export { default as CustomerExperienceImage } from "../assets/bfsi/customer_exp.svg";
export { default as CustomerServiceImage } from "../assets/bfsi/customer_service.svg";
export { default as CustomerSupportImage } from "../assets/bfsi/customer_support.svg";
// export { default as FinancalAdvisorImage } from '../assets/bfsi/financal_advisor.png';
// export { default as FraudDeductionImage } from '../assets/bfsi/fraud_deduction.png';
// export { default as InsuranceImage } from '../assets/bfsi/insurance.png';
// export { default as LoanProcessingImage } from '../assets/bfsi/loan_processing.png';
// export { default as RegulatoryComplianceImage } from '../assets/bfsi/regulatory_compliance.png';
// export { default as RetailBankingImage } from '../assets/bfsi/retail_and_banking.png';
// export { default as SalesDistriutionAndCustomerExpImage } from '../assets/bfsi/sales_and_distributon_and_cutomer_exp.png';
// export { default as UnderWrittingImage } from '../assets/bfsi/under_writting.png';
// // new images
export { default as HealthTechBannerImage } from "../assets/healthcare/health_tech_banner.png";
export { default as HealthcarePlayerBannerImage } from "../assets/healthcare/healthcare_player_banner.png";
export { default as HeathcareProviderBannerImage } from "../assets/healthcare/healthcare_provider_banner.png";

// // new image
export { default as EducationBannerImage } from "../assets/multimedia/education_banner.png";
export { default as GamingAndSportBannerImage } from "../assets/multimedia/gaming_and_sport_banner.png";
export { default as MediaAndBroadcastBannerImage } from "../assets/multimedia/media_and_broadcast_banner.png";
export { default as MulimediaHeroBannerImage } from "../assets/multimedia/multimedia_hero_banner.png";
export { default as TelecomBannerImage } from "../assets/multimedia/telecom_banner.png";

export { default as CapitalMarketing } from "../assets/bfsi/capital_marketing.png";
export { default as InsuranceBanner } from "../assets/bfsi/insurance_banner.png";
export { default as RetailAndCommercial } from "../assets/bfsi/retail_and_commercial_banking_banner.png";
export { default as AiChainingImage } from "../assets/svg/Images/AiChainingImage.svg";
export { default as AutomacticImage } from "../assets/svg/Images/AutomacticImage.svg";
export { default as DeployImage } from "../assets/svg/Images/DeployImage.svg";
export { default as ImproveImage } from "../assets/svg/Images/ImproveImage.svg";
export { default as IsoIcon } from "../assets/svg/Images/IsoIcon.svg";
export { default as ModelFeatureImage } from "../assets/svg/Images/ModelFeatureImage.svg";
export { default as ReadilyImage } from "../assets/svg/Images/ReadilyImage.svg";
export { default as SocIcon } from "../assets/svg/Images/SocIcon.svg";
export { default as TraceVisibilityImage } from "../assets/svg/Images/TraceVisibilityImage.svg";
export { default as cloudDeploy } from "../assets/svg/Images/cloudDeploy.svg";
export { default as CoinHourglass } from "../assets/svg/Images/coinHourglass.svg";
export { default as intelligentAi } from "../assets/svg/Images/intelligentAi.svg";
export { default as SecureAi } from "../assets/svg/Images/secure-ai.svg";
//
export { default as ConsultingBanner } from "../assets/legal/consulting_banner.png";
export { default as LegalBanner } from "../assets/legal/legal_banner.png";
export { default as ResearchBanner } from "../assets/legal/research_banner.png";
export { default as AiEncryption } from "../assets/svg/Images/AiEncryption.svg";
export { default as AnalysisAgentIcon } from "../assets/svg/Images/AnalysisAgentIcon.svg";
export { default as ApiIcon } from "../assets/svg/Images/ApiIcon.svg";
export { default as ChatbotFeatureImage } from "../assets/svg/Images/ChatbotFeatureImage.svg";
export { default as CitationImage } from "../assets/svg/Images/CitationImage.svg";
export { default as ConnectionIcon } from "../assets/svg/Images/ConnectionIcon.svg";
export { default as CustomerSupportIcon } from "../assets/svg/Images/CustomerSupportIcon.svg";
export { default as DomainAgent } from "../assets/svg/Images/DomainAgent.svg";
export { default as EmbedIcon } from "../assets/svg/Images/EmbedIcon.svg";
export { default as EmployeeAssistantIcon } from "../assets/svg/Images/EmployeeAssistantIcon.svg";
export { default as EvaluationImage } from "../assets/svg/Images/EvaluationImage.svg";
export { default as FrameworkImage } from "../assets/svg/Images/FrameworkImage.svg";
export { default as GuardrailsImage } from "../assets/svg/Images/GuardrailsImage.svg";
export { default as HealthcareImage } from "../assets/svg/Images/HealthcareImage.svg";
export { default as InsuranceImage } from "../assets/svg/Images/InsuranceImage.svg";
export { default as InternetImage } from "../assets/svg/Images/InternetImage.svg";
export { default as KnowledgeAssistantIcon } from "../assets/svg/Images/KnowledgeAssistantIcon.svg";
export { default as LegalImage } from "../assets/svg/Images/LegalImage.svg";
export { default as MarketingIcon } from "../assets/svg/Images/MarketingIcon.svg";
export { default as MobileSdkIcon } from "../assets/svg/Images/MobileSdkIcon.svg";
export { default as ResearchIcon } from "../assets/svg/Images/ResearchIcon.svg";
export { default as ScalabilityIcon } from "../assets/svg/Images/ScalabilityIcon.svg";
export { default as SecurityIcon } from "../assets/svg/Images/SecurityIcon.svg";
export { default as SpeedIcon } from "../assets/svg/Images/Speed_Icon.svg";
export { default as TaskIcon } from "../assets/svg/Images/TaskIcon.svg";
export { default as TelecomImage } from "../assets/svg/Images/TelecomImage.svg";
export { default as chatbotImage } from "../assets/svg/Images/chatbotImage.svg";
